// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfyvigdhtigqzuzokivb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmeXZpZ2RodGlncXp1em9raXZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODgyMDQsImV4cCI6MjA2MDA2NDIwNH0.mFF6Kun7JE_DKxVdhtGcp6DDCZD_sywra4qqEfbYVcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);